/*
 * This file was automatically generated by EvoSuite
 * Thu Oct 01 16:36:43 GMT 2026
 */

package org.apache.commons.lang3;

import org.junit.Test;
import static org.junit.Assert.*;
import java.io.File;
import org.apache.commons.lang3.SystemUtils;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.testdata.EvoSuiteFile;
import org.evosuite.runtime.testdata.FileSystemHandling;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class SystemUtils_ESTest extends SystemUtils_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      float float0 = SystemUtils.toJavaVersionInt("d3@l/R*{R_&");
      assertEquals(300.0F, float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      boolean boolean0 = SystemUtils.isJavaVersionAtLeast(180);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      boolean boolean0 = SystemUtils.isJavaVersionAtLeast(1.8F);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      int[] intArray0 = SystemUtils.toJavaVersionIntArray("0';%h=!t|uN$vK Mg");
      assertEquals(1, intArray0.length);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      boolean boolean0 = SystemUtils.isOSNameMatch("Windows", "Windows");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("/home/pizza/TestRound2/results/project-Lang/Lang-29/round03/evosuite-work");
      FileSystemHandling.setPermissions(evoSuiteFile0, false, false, false);
      File file0 = SystemUtils.getUserDir();
      assertFalse(file0.isHidden());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("/tmp");
      FileSystemHandling.setPermissions(evoSuiteFile0, true, false, false);
      File file0 = SystemUtils.getJavaIoTmpDir();
      assertEquals("/", file0.getParent());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("/usr/lib/jvm/java-8-openjdk-amd64/jre");
      FileSystemHandling.createFolder(evoSuiteFile0);
      File file0 = SystemUtils.getJavaHome();
      assertEquals(0L, file0.getUsableSpace());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("/usr/lib/jvm/java-8-openjdk-amd64/jre");
      FileSystemHandling.appendStringToFile(evoSuiteFile0, "Java Platform API Specification");
      File file0 = SystemUtils.getJavaHome();
      assertEquals("/usr/lib/jvm/java-8-openjdk-amd64/jre", file0.toString());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      float float0 = SystemUtils.toJavaVersionFloat("");
      assertEquals(0.0F, float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      float float0 = SystemUtils.toJavaVersionFloat("os.arch");
      assertEquals(0.0F, float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      float float0 = SystemUtils.toJavaVersionInt((String) null);
      assertEquals(0.0F, float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      boolean boolean0 = SystemUtils.isOSNameMatch((String) null, "");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      boolean boolean0 = SystemUtils.isOSMatch("", "", "", "");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      boolean boolean0 = SystemUtils.isOSMatch("sun.awt.X11GraphicsEnvironment", "4.0", "sun.awt.X11GraphicsEnvironment", "1:b:VV0");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      boolean boolean0 = SystemUtils.isOSMatch(" in an array of ", (String) null, "25.504-b01", "52.0");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      boolean boolean0 = SystemUtils.isOSMatch("1.51.8.0_504", "1.51.8.0_504", "{}", " CFQG0");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      boolean boolean0 = SystemUtils.isOSMatch((String) null, "Mac OS XLinux", "r!em;[F>CW", "Java Platform API Specification");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      boolean boolean0 = SystemUtils.isJavaVersionMatch((String) null, "{}");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      boolean boolean0 = SystemUtils.isJavaVersionMatch("", "");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      boolean boolean0 = SystemUtils.isJavaVersionAtLeast((-598));
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      boolean boolean0 = SystemUtils.isJavaVersionAtLeast(Integer.MAX_VALUE);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      boolean boolean0 = SystemUtils.isJavaVersionAtLeast(0.0F);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      boolean boolean0 = SystemUtils.isJavaVersionAtLeast(98.0F);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      boolean boolean0 = SystemUtils.isJavaAwtHeadless();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      SystemUtils systemUtils0 = new SystemUtils();
      assertEquals(180, SystemUtils.JAVA_VERSION_INT);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      File file0 = SystemUtils.getUserHome();
      assertEquals("pizza", file0.getName());
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      File file0 = SystemUtils.getUserDir();
      assertEquals("/home/pizza/TestRound2/results/project-Lang/Lang-29/round03", file0.getParent());
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      File file0 = SystemUtils.getJavaHome();
      assertTrue(file0.isFile());
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      File file0 = SystemUtils.getJavaIoTmpDir();
      assertTrue(file0.isDirectory());
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      float float0 = SystemUtils.toJavaVersionInt("1.31.8.0_504");
      assertEquals(418.0F, float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      int[] intArray0 = SystemUtils.toJavaVersionIntArray("Cannot store ");
      assertEquals(0, intArray0.length);
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      float float0 = SystemUtils.toJavaVersionFloat("/usr/lib/jvm/java-8-openjdk-amd64/jre");
      assertEquals(8.64F, float0, 0.01F);
  }
}
