/*
 * This file was automatically generated by EvoSuite
 * Wed Sep 30 13:16:16 GMT 2026
 */

package org.apache.commons.lang3.math;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.commons.lang3.math.Fraction;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Fraction_ESTest extends Fraction_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Fraction fraction0 = Fraction.TWO_FIFTHS;
      Fraction fraction1 = fraction0.TWO_QUARTERS.reduce();
      int int0 = fraction1.compareTo(fraction0);
      assertEquals(1, fraction1.getNumerator());
      assertEquals(1, int0);
      assertEquals((short)0, fraction1.shortValue());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Fraction fraction0 = Fraction.getFraction(12, 12, 1056);
      // Undeclared exception!
      try { 
        fraction0.pow((-421));
        fail("Expecting exception: ArithmeticException");
      
      } catch(ArithmeticException e) {
         //
         // overflow: mulPos
         //
         verifyException("org.apache.commons.lang3.math.Fraction", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Fraction fraction0 = Fraction.ONE_THIRD;
      Fraction fraction1 = Fraction.getFraction((-1.0));
      Fraction fraction2 = fraction1.subtract(fraction0);
      assertEquals((-1.3333333333333333), fraction2.doubleValue(), 0.01);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Fraction fraction0 = Fraction.THREE_QUARTERS;
      Fraction fraction1 = Fraction.ONE_FIFTH;
      Fraction fraction2 = fraction1.subtract(fraction0);
      Fraction fraction3 = fraction2.reduce();
      assertEquals((-0.55), fraction3.doubleValue(), 0.01);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Fraction fraction0 = Fraction.getFraction(12, 12, 1056);
      Fraction fraction1 = fraction0.reduce();
      assertEquals(1057, fraction1.getNumerator());
      assertEquals(1, fraction1.getProperNumerator());
      assertEquals(12, fraction0.intValue());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Fraction fraction0 = Fraction.getFraction(10000, (-2306));
      Fraction fraction1 = fraction0.ZERO.negate();
      assertEquals(0.0F, fraction1.floatValue(), 0.01F);
      assertEquals(2306, fraction0.getDenominator());
      assertEquals((-4.3365135F), fraction0.floatValue(), 0.01F);
      assertEquals(1, fraction1.getDenominator());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Fraction fraction0 = Fraction.FOUR_FIFTHS;
      Fraction fraction1 = Fraction.getFraction(2605, 388, 2605);
      Fraction fraction2 = fraction0.multiplyBy(fraction1);
      assertEquals(2084.1191554702496, fraction2.doubleValue(), 0.01);
      assertEquals((short)2605, fraction1.shortValue());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Fraction fraction0 = Fraction.TWO_FIFTHS;
      Fraction fraction1 = Fraction.getReducedFraction((-2726), 304);
      Fraction fraction2 = fraction1.multiplyBy(fraction0);
      assertEquals(380, fraction2.getDenominator());
      assertEquals((-8.967105263157896), fraction1.doubleValue(), 0.01);
      assertEquals((byte) (-3), fraction2.byteValue());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Fraction fraction0 = Fraction.ONE_FIFTH;
      Fraction fraction1 = fraction0.invert();
      assertEquals(1, fraction1.getDenominator());
      assertEquals(5.0F, fraction1.floatValue(), 0.01F);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Fraction fraction0 = Fraction.getFraction(2605, 388, 2605);
      Fraction fraction1 = fraction0.invert();
      assertEquals(2605, fraction1.getNumerator());
      assertEquals(2605, fraction0.getProperWhole());
      assertEquals(6786413, fraction1.getDenominator());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Fraction fraction0 = Fraction.FOUR_FIFTHS;
      Fraction fraction1 = fraction0.TWO_FIFTHS.invert();
      int int0 = fraction1.intValue();
      assertEquals(5, fraction1.getNumerator());
      assertEquals(2, int0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Fraction fraction0 = Fraction.getReducedFraction((-1879), (-1579));
      assertEquals(1.1899936F, fraction0.floatValue(), 0.01F);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Fraction fraction0 = Fraction.getFraction(12, 12, 1056);
      int int0 = fraction0.getProperWhole();
      assertEquals(12.011363636363637, fraction0.doubleValue(), 0.01);
      assertEquals(12, int0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Fraction fraction0 = Fraction.THREE_FIFTHS;
      int int0 = fraction0.getNumerator();
      assertEquals(3, int0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Fraction fraction0 = Fraction.getFraction(2026, 2026);
      Fraction fraction1 = fraction0.TWO_THIRDS.negate();
      Fraction fraction2 = fraction1.invert();
      assertEquals(2026, fraction0.getNumerator());
      assertEquals((-1.5), fraction2.doubleValue(), 0.01);
      assertEquals(1.0F, fraction0.floatValue(), 0.01F);
      assertEquals((-3), fraction2.getNumerator());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Fraction fraction0 = Fraction.getReducedFraction((-2726), 304);
      Fraction fraction1 = fraction0.THREE_QUARTERS.add(fraction0);
      assertEquals((-8.217105F), fraction1.floatValue(), 0.01F);
      assertEquals(33, fraction1.getProperNumerator());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Fraction fraction0 = Fraction.getReducedFraction(31, (-1));
      assertEquals((-31), fraction0.getNumerator());
      assertEquals((-31.0F), fraction0.floatValue(), 0.01F);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Fraction fraction0 = Fraction.getReducedFraction(0, (-448));
      assertEquals(1, fraction0.getDenominator());
      assertEquals(0L, fraction0.longValue());
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Fraction fraction0 = Fraction.getFraction(10000, (-2306));
      int int0 = fraction0.getNumerator();
      assertEquals((-4.336513443191674), fraction0.doubleValue(), 0.01);
      assertEquals((-10000), int0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Fraction fraction0 = Fraction.getFraction(10000, (-2306));
      int int0 = fraction0.getProperWhole();
      assertEquals((-4), int0);
      assertEquals((-4.3365135F), fraction0.floatValue(), 0.01F);
      assertEquals((-10000), fraction0.getNumerator());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Fraction fraction0 = Fraction.getFraction(10000, (-2306));
      int int0 = fraction0.getDenominator();
      assertEquals(2306, int0);
      assertEquals((-4.336513443191674), fraction0.doubleValue(), 0.01);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Fraction fraction0 = Fraction.ONE_QUARTER;
      String string0 = fraction0.toProperString();
      assertEquals("1/4", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Fraction fraction0 = Fraction.getFraction(10000, (-2306));
      String string0 = fraction0.toProperString();
      assertNotNull(string0);
      assertEquals("-4 776/2306", string0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Fraction fraction0 = Fraction.THREE_FIFTHS;
      Fraction fraction1 = fraction0.ONE.abs();
      Fraction fraction2 = Fraction.getFraction(47, 47);
      assertEquals(47, fraction2.getDenominator());
      
      Fraction fraction3 = fraction0.ZERO.add(fraction1);
      int int0 = fraction0.getProperNumerator();
      assertEquals(3, int0);
      
      Fraction fraction4 = fraction0.ONE_THIRD.add(fraction1);
      fraction4.ZERO.toProperString();
      assertEquals(1.3333333333333333, fraction4.doubleValue(), 0.01);
      
      Fraction fraction5 = Fraction.getFraction(1.0);
      assertTrue(fraction5.equals((Object)fraction3));
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Fraction fraction0 = Fraction.TWO_FIFTHS;
      Fraction fraction1 = fraction0.TWO_QUARTERS.reduce();
      String string0 = fraction1.toString();
      assertEquals("1/2", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Fraction fraction0 = Fraction.TWO_FIFTHS;
      Fraction fraction1 = fraction0.TWO_QUARTERS.reduce();
      Fraction fraction2 = Fraction.getFraction("1");
      int int0 = fraction1.compareTo(fraction2);
      assertEquals((-1), int0);
      assertEquals(2, fraction1.getDenominator());
      assertEquals(1, fraction1.getProperNumerator());
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Fraction fraction0 = Fraction.TWO_FIFTHS;
      Fraction fraction1 = fraction0.THREE_FIFTHS.subtract(fraction0);
      int int0 = fraction0.compareTo(fraction1);
      assertEquals(5, fraction1.getDenominator());
      assertEquals(1, int0);
      assertEquals(1, fraction1.getNumerator());
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Fraction fraction0 = Fraction.ONE_QUARTER;
      Fraction fraction1 = fraction0.TWO_THIRDS.reduce();
      fraction0.ONE_QUARTER.hashCode();
      Fraction fraction2 = fraction1.TWO_FIFTHS.pow(12);
      assertEquals(1.6777216E-5F, fraction2.floatValue(), 0.01F);
      assertEquals(244140625, fraction2.getDenominator());
      
      Fraction fraction3 = Fraction.getFraction(12, 12, 1056);
      assertEquals(12684, fraction3.getNumerator());
      
      Fraction fraction4 = Fraction.TWO_THIRDS;
      Fraction fraction5 = fraction4.FOUR_FIFTHS.negate();
      assertEquals((-4), fraction5.getNumerator());
      assertSame(fraction4, fraction1);
      
      Fraction fraction6 = Fraction.getFraction(0, 12, 12);
      assertEquals(12, fraction6.getNumerator());
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      Fraction fraction0 = Fraction.ONE_QUARTER;
      fraction0.ONE_QUARTER.hashCode();
      assertEquals(4, fraction0.getDenominator());
      assertEquals(1, fraction0.getNumerator());
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      Fraction fraction0 = Fraction.TWO_FIFTHS;
      Object object0 = new Object();
      boolean boolean0 = fraction0.equals(object0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      Fraction fraction0 = Fraction.FOUR_FIFTHS;
      Fraction fraction1 = fraction0.ZERO.multiplyBy(fraction0);
      assertEquals(0.0F, fraction1.floatValue(), 0.01F);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      Fraction fraction0 = Fraction.getFraction(2026, 2026);
      Fraction fraction1 = Fraction.getFraction(1469.3907);
      // Undeclared exception!
      try { 
        fraction0.add(fraction1);
        fail("Expecting exception: ArithmeticException");
      
      } catch(ArithmeticException e) {
         //
         // overflow: numerator too large after multiply
         //
         verifyException("org.apache.commons.lang3.math.Fraction", e);
      }
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      Fraction fraction0 = Fraction.FOUR_FIFTHS;
      Fraction fraction1 = Fraction.getFraction(0.0);
      Fraction fraction2 = fraction0.ONE_QUARTER.subtract(fraction1);
      Fraction fraction3 = fraction2.TWO_FIFTHS.invert();
      assertEquals(0.25F, fraction2.floatValue(), 0.01F);
      assertEquals(2.5F, fraction3.floatValue(), 0.01F);
      
      fraction0.ONE.toProperString();
      assertNotSame(fraction0, fraction1);
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      Fraction fraction0 = Fraction.getFraction(0, 1264);
      Fraction fraction1 = fraction0.subtract(fraction0);
      assertTrue(fraction1.equals((Object)fraction0));
      assertEquals(1264, fraction1.getDenominator());
      assertNotSame(fraction1, fraction0);
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      Fraction fraction0 = Fraction.THREE_FIFTHS;
      Fraction fraction1 = fraction0.ZERO.add(fraction0);
      assertSame(fraction1, fraction0);
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      Fraction fraction0 = Fraction.FOUR_FIFTHS;
      // Undeclared exception!
      try { 
        fraction0.ONE_THIRD.pow(1579);
        fail("Expecting exception: ArithmeticException");
      
      } catch(ArithmeticException e) {
         //
         // overflow: mulPos
         //
         verifyException("org.apache.commons.lang3.math.Fraction", e);
      }
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      Fraction fraction0 = Fraction.ONE_QUARTER;
      // Undeclared exception!
      try { 
        fraction0.pow((-421));
        fail("Expecting exception: ArithmeticException");
      
      } catch(ArithmeticException e) {
         //
         // overflow: mul
         //
         verifyException("org.apache.commons.lang3.math.Fraction", e);
      }
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      Fraction fraction0 = Fraction.THREE_FIFTHS;
      Fraction fraction1 = fraction0.pow(0);
      assertEquals(1.0F, fraction1.floatValue(), 0.01F);
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      Fraction fraction0 = Fraction.FOUR_FIFTHS;
      Fraction fraction1 = fraction0.abs();
      assertEquals(4, fraction1.getNumerator());
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      Fraction fraction0 = Fraction.getFraction(10000, (-2306));
      Fraction fraction1 = fraction0.abs();
      long long0 = fraction1.longValue();
      assertEquals(4.336513443191674, fraction1.doubleValue(), 0.01);
      assertEquals((-10000), fraction0.getNumerator());
      assertEquals(4L, long0);
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      Fraction fraction0 = Fraction.ONE_THIRD;
      Fraction fraction1 = Fraction.getFraction((-1.0));
      Fraction fraction2 = fraction0.divideBy(fraction1);
      assertEquals((-0.3333333333333333), fraction2.doubleValue(), 0.01);
      assertEquals((-1), fraction1.getProperWhole());
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      Fraction fraction0 = Fraction.ONE_QUARTER;
      Fraction fraction1 = fraction0.divideBy(fraction0);
      assertEquals(1, fraction1.getDenominator());
      assertEquals(1.0F, fraction1.floatValue(), 0.01F);
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      Fraction fraction0 = Fraction.ONE_QUARTER;
      Fraction fraction1 = fraction0.TWO_THIRDS.reduce();
      boolean boolean0 = fraction0.equals(fraction1);
      assertFalse(boolean0);
      assertEquals(2, fraction1.getNumerator());
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      Fraction fraction0 = Fraction.getFraction(2026, 2026);
      Fraction fraction1 = fraction0.ZERO.reduce();
      assertEquals(2026, fraction0.getNumerator());
      assertFalse(fraction1.equals((Object)fraction0));
      assertEquals(1.0F, fraction0.floatValue(), 0.01F);
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      Fraction fraction0 = Fraction.TWO_FIFTHS;
      Fraction fraction1 = fraction0.TWO_QUARTERS.reduce();
      Fraction fraction2 = Fraction.getFraction("1");
      boolean boolean0 = fraction2.equals(fraction1);
      assertFalse(fraction1.equals((Object)fraction2));
      assertEquals(0.5, fraction1.doubleValue(), 0.01);
      assertEquals(1, fraction1.getProperNumerator());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      Fraction fraction0 = Fraction.getFraction("2/5");
      assertEquals(5, fraction0.getDenominator());
      assertEquals(0.4F, fraction0.floatValue(), 0.01F);
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      // Undeclared exception!
      try { 
        Fraction.getFraction("overflow: mul");
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // For input string: \"overflow:\"
         //
         verifyException("java.lang.NumberFormatException", e);
      }
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      Fraction fraction0 = Fraction.getFraction("1");
      Fraction fraction1 = Fraction.getFraction((-1), (-1));
      int int0 = fraction1.compareTo(fraction0);
      assertEquals(0, fraction0.getProperNumerator());
      assertEquals(1.0, fraction1.doubleValue(), 0.01);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      Fraction fraction0 = Fraction.getFraction((-1.0));
      Fraction fraction1 = fraction0.pow((-1879));
      assertEquals((-1), fraction1.intValue());
      assertEquals((-1L), fraction0.longValue());
  }

  @Test(timeout = 4000)
  public void test49()  throws Throwable  {
      Fraction fraction0 = Fraction.getReducedFraction(44, Integer.MIN_VALUE);
      Fraction fraction1 = Fraction.getFraction(3223, 6, 629);
      // Undeclared exception!
      try { 
        fraction1.divideBy(fraction0);
        fail("Expecting exception: ArithmeticException");
      
      } catch(ArithmeticException e) {
         //
         // overflow: mul
         //
         verifyException("org.apache.commons.lang3.math.Fraction", e);
      }
  }

  @Test(timeout = 4000)
  public void test50()  throws Throwable  {
      Fraction fraction0 = Fraction.getFraction((double) 0);
      int int0 = fraction0.getProperNumerator();
      assertEquals(0, int0);
      assertEquals(0.0, fraction0.doubleValue(), 0.01);
  }

  @Test(timeout = 4000)
  public void test51()  throws Throwable  {
      // Undeclared exception!
      try { 
        Fraction.getReducedFraction((-540), 0);
        fail("Expecting exception: ArithmeticException");
      
      } catch(ArithmeticException e) {
         //
         // The denominator must not be zero
         //
         verifyException("org.apache.commons.lang3.math.Fraction", e);
      }
  }

  @Test(timeout = 4000)
  public void test52()  throws Throwable  {
      Fraction fraction0 = Fraction.getFraction((-1), 82, 3307);
      assertEquals((-1.0247958875113397), fraction0.doubleValue(), 0.01);
  }

  @Test(timeout = 4000)
  public void test53()  throws Throwable  {
      // Undeclared exception!
      try { 
        Fraction.getFraction(1, (-5456), 3223);
        fail("Expecting exception: ArithmeticException");
      
      } catch(ArithmeticException e) {
         //
         // The numerator must not be negative
         //
         verifyException("org.apache.commons.lang3.math.Fraction", e);
      }
  }

  @Test(timeout = 4000)
  public void test54()  throws Throwable  {
      Fraction fraction0 = Fraction.ONE_QUARTER;
      Fraction fraction1 = fraction0.subtract(fraction0);
      assertEquals(1, fraction1.getDenominator());
      assertEquals((byte)0, fraction1.byteValue());
  }

  @Test(timeout = 4000)
  public void test55()  throws Throwable  {
      Fraction fraction0 = Fraction.ONE_QUARTER;
      double double0 = fraction0.doubleValue();
      assertEquals(0.25, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test56()  throws Throwable  {
      Fraction fraction0 = Fraction.getFraction(12, 12, 1056);
      String string0 = fraction0.toProperString();
      assertNotNull(string0);
      assertEquals("12 12/1056", string0);
  }

  @Test(timeout = 4000)
  public void test57()  throws Throwable  {
      Fraction fraction0 = Fraction.FOUR_FIFTHS;
      Fraction fraction1 = Fraction.ONE_FIFTH;
      Fraction fraction2 = fraction0.ONE_FIFTH.multiplyBy(fraction1);
      fraction2.TWO_FIFTHS.toString();
      Fraction fraction3 = Fraction.getFraction(2605, 388, 2605);
      Fraction fraction4 = fraction3.ONE_QUARTER.multiplyBy(fraction2);
      fraction4.ONE_QUARTER.negate();
      Fraction fraction5 = fraction4.ONE_THIRD.negate();
      assertEquals((-1), fraction5.getNumerator());
      assertEquals(100, fraction4.getDenominator());
      assertEquals(1, fraction2.getNumerator());
      assertEquals(6786413, fraction3.getNumerator());
      
      long long0 = fraction0.longValue();
      assertEquals(0L, long0);
      
      Fraction fraction6 = Fraction.ONE_THIRD;
      Fraction fraction7 = Fraction.getFraction(2605, 2605);
      assertEquals(1.0, fraction7.doubleValue(), 0.01);
  }

  @Test(timeout = 4000)
  public void test58()  throws Throwable  {
      Fraction fraction0 = Fraction.FOUR_FIFTHS;
      int int0 = fraction0.intValue();
      assertEquals(0, int0);
  }
}
