/*
 * This file was automatically generated by EvoSuite
 * Thu Oct 01 18:19:25 GMT 2026
 */

package com.fasterxml.jackson.databind.ser.std;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.JavaType;
import com.fasterxml.jackson.databind.SerializationConfig;
import com.fasterxml.jackson.databind.cfg.MapperConfig;
import com.fasterxml.jackson.databind.introspect.AnnotatedClass;
import com.fasterxml.jackson.databind.introspect.BasicBeanDescription;
import com.fasterxml.jackson.databind.introspect.ObjectIdInfo;
import com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector;
import com.fasterxml.jackson.databind.ser.std.EnumSerializer;
import com.fasterxml.jackson.databind.util.EnumValues;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class EnumSerializer_ESTest extends EnumSerializer_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Class<Object> class0 = Object.class;
      JsonFormat.Shape jsonFormat_Shape0 = JsonFormat.Shape.OBJECT;
      JsonFormat.Value jsonFormat_Value0 = JsonFormat.Value.forShape(jsonFormat_Shape0);
      // Undeclared exception!
      try { 
        EnumSerializer._isShapeWrittenUsingIndex(class0, jsonFormat_Value0, false);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Unsupported serialization shape (OBJECT) for Enum java.lang.Object, not supported as property annotation
         //
         verifyException("com.fasterxml.jackson.databind.ser.std.EnumSerializer", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Class<Object> class0 = Object.class;
      JsonFormat.Shape jsonFormat_Shape0 = JsonFormat.Shape.OBJECT;
      JsonFormat.Value jsonFormat_Value0 = JsonFormat.Value.forShape(jsonFormat_Shape0);
      // Undeclared exception!
      try { 
        EnumSerializer._isShapeWrittenUsingIndex(class0, jsonFormat_Value0, true);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Unsupported serialization shape (OBJECT) for Enum java.lang.Object, not supported as class annotation
         //
         verifyException("com.fasterxml.jackson.databind.ser.std.EnumSerializer", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Class<JsonParser.Feature> class0 = JsonParser.Feature.class;
      JsonFormat.Shape jsonFormat_Shape0 = JsonFormat.Shape.ARRAY;
      JsonFormat.Value jsonFormat_Value0 = JsonFormat.Value.forShape(jsonFormat_Shape0);
      Boolean boolean0 = EnumSerializer._isShapeWrittenUsingIndex(class0, jsonFormat_Value0, false);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Class<Object> class0 = Object.class;
      JsonFormat.Shape jsonFormat_Shape0 = JsonFormat.Shape.NATURAL;
      JsonFormat.Value jsonFormat_Value0 = JsonFormat.Value.forShape(jsonFormat_Shape0);
      Boolean boolean0 = EnumSerializer._isShapeWrittenUsingIndex(class0, jsonFormat_Value0, true);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Class<Object> class0 = Object.class;
      JsonFormat.Shape jsonFormat_Shape0 = JsonFormat.Shape.STRING;
      JsonFormat.Value jsonFormat_Value0 = JsonFormat.Value.forShape(jsonFormat_Shape0);
      Boolean boolean0 = EnumSerializer._isShapeWrittenUsingIndex(class0, jsonFormat_Value0, false);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Class<Object> class0 = Object.class;
      JsonFormat.Shape jsonFormat_Shape0 = JsonFormat.Shape.SCALAR;
      JsonFormat.Value jsonFormat_Value0 = new JsonFormat.Value("", jsonFormat_Shape0, "", "", (JsonFormat.Features) null);
      Boolean boolean0 = EnumSerializer._isShapeWrittenUsingIndex(class0, jsonFormat_Value0, true);
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      JsonFormat.Value jsonFormat_Value0 = new JsonFormat.Value();
      Class<JsonParser.Feature> class0 = JsonParser.Feature.class;
      Boolean boolean0 = EnumSerializer._isShapeWrittenUsingIndex(class0, jsonFormat_Value0, true);
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Class<Object> class0 = Object.class;
      Boolean boolean0 = EnumSerializer._isShapeWrittenUsingIndex(class0, (JsonFormat.Value) null, true);
      assertNull(boolean0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Class<Object> class0 = Object.class;
      JsonFormat.Value jsonFormat_Value0 = new JsonFormat.Value();
      POJOPropertiesCollector pOJOPropertiesCollector0 = mock(POJOPropertiesCollector.class, new ViolatedAssumptionAnswer());
      doReturn((AnnotatedClass) null).when(pOJOPropertiesCollector0).getClassDef();
      doReturn((MapperConfig) null).when(pOJOPropertiesCollector0).getConfig();
      doReturn((ObjectIdInfo) null).when(pOJOPropertiesCollector0).getObjectIdInfo();
      doReturn((JavaType) null).when(pOJOPropertiesCollector0).getType();
      BasicBeanDescription basicBeanDescription0 = BasicBeanDescription.forSerialization(pOJOPropertiesCollector0);
      // Undeclared exception!
      try { 
        EnumSerializer.construct(class0, (SerializationConfig) null, basicBeanDescription0, jsonFormat_Value0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.fasterxml.jackson.databind.util.EnumValues", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Class<Object> class0 = Object.class;
      JsonFormat.Shape jsonFormat_Shape0 = JsonFormat.Shape.NUMBER;
      JsonFormat.Value jsonFormat_Value0 = JsonFormat.Value.forShape(jsonFormat_Shape0);
      Boolean boolean0 = EnumSerializer._isShapeWrittenUsingIndex(class0, jsonFormat_Value0, false);
      EnumSerializer enumSerializer0 = null;
      try {
        enumSerializer0 = new EnumSerializer((EnumValues) null, boolean0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.fasterxml.jackson.databind.ser.std.EnumSerializer", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      EnumSerializer enumSerializer0 = null;
      try {
        enumSerializer0 = new EnumSerializer((EnumValues) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.fasterxml.jackson.databind.ser.std.EnumSerializer", e);
      }
  }
}
