/*
 * This file was automatically generated by EvoSuite
 * Wed Sep 30 22:16:09 GMT 2026
 */

package com.fasterxml.jackson.databind.type;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.fasterxml.jackson.databind.JavaType;
import com.fasterxml.jackson.databind.type.CollectionLikeType;
import com.fasterxml.jackson.databind.type.CollectionType;
import com.fasterxml.jackson.databind.type.MapType;
import com.fasterxml.jackson.databind.type.PlaceholderForType;
import com.fasterxml.jackson.databind.type.ReferenceType;
import com.fasterxml.jackson.databind.type.ResolvedRecursiveType;
import com.fasterxml.jackson.databind.type.SimpleType;
import com.fasterxml.jackson.databind.type.TypeBindings;
import com.fasterxml.jackson.databind.type.TypeFactory;
import com.fasterxml.jackson.databind.util.LRUMap;
import java.time.format.ResolverStyle;
import java.util.HashMap;
import java.util.LinkedHashSet;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.testdata.FileSystemHandling;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class ReferenceType_ESTest extends ReferenceType_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Class<Object> class0 = Object.class;
      JavaType javaType0 = TypeFactory.unknownType();
      JavaType[] javaTypeArray0 = new JavaType[5];
      javaTypeArray0[4] = javaType0;
      ReferenceType referenceType0 = ReferenceType.construct(class0, (TypeBindings) null, javaType0, javaTypeArray0, javaTypeArray0[4]);
      ReferenceType referenceType1 = referenceType0.withStaticTyping();
      ReferenceType referenceType2 = referenceType1.withValueHandler(referenceType1);
      assertTrue(referenceType2.equals((Object)referenceType0));
      assertFalse(referenceType2.isAnchorType());
      assertFalse(referenceType1.isAnchorType());
      assertTrue(referenceType2.useStaticType());
      assertTrue(referenceType0.isAnchorType());
      assertTrue(referenceType2.hasValueHandler());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Class<ResolverStyle> class0 = ResolverStyle.class;
      SimpleType simpleType0 = new SimpleType(class0);
      ReferenceType referenceType0 = ReferenceType.upgradeFrom(simpleType0, simpleType0);
      ReferenceType referenceType1 = referenceType0.withValueHandler(simpleType0);
      assertFalse(referenceType1.isAnchorType());
      assertTrue(referenceType1.equals((Object)referenceType0));
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      FileSystemHandling fileSystemHandling0 = new FileSystemHandling();
      SimpleType simpleType0 = TypeFactory.CORE_TYPE_INT;
      ReferenceType referenceType0 = ReferenceType.upgradeFrom(simpleType0, simpleType0);
      ReferenceType referenceType1 = referenceType0.withValueHandler(fileSystemHandling0);
      assertFalse(referenceType1.isAnchorType());
      assertTrue(referenceType1.equals((Object)referenceType0));
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      TypeFactory typeFactory0 = TypeFactory.defaultInstance();
      Class<HashMap> class0 = HashMap.class;
      MapType mapType0 = typeFactory0.constructRawMapType(class0);
      ReferenceType referenceType0 = new ReferenceType(mapType0, mapType0);
      Object object0 = new Object();
      ReferenceType referenceType1 = referenceType0.withValueHandler(object0);
      assertFalse(referenceType1.isAnchorType());
      assertTrue(referenceType1.equals((Object)referenceType0));
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      SimpleType simpleType0 = TypeFactory.CORE_TYPE_INT;
      ReferenceType referenceType0 = new ReferenceType(simpleType0, simpleType0);
      Class<ResolverStyle> class0 = ResolverStyle.class;
      ReferenceType referenceType1 = referenceType0.withTypeHandler(class0);
      assertTrue(referenceType1.equals((Object)referenceType0));
      assertFalse(referenceType1.isAnchorType());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Class<ResolverStyle> class0 = ResolverStyle.class;
      SimpleType simpleType0 = new SimpleType(class0);
      ReferenceType referenceType0 = ReferenceType.upgradeFrom(simpleType0, simpleType0);
      Object object0 = new Object();
      ReferenceType referenceType1 = referenceType0.withTypeHandler(object0);
      assertTrue(referenceType1.equals((Object)referenceType0));
      assertFalse(referenceType1.isAnchorType());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Class<ResolvedRecursiveType> class0 = ResolvedRecursiveType.class;
      Class<Object> class1 = Object.class;
      SimpleType simpleType0 = TypeFactory.CORE_TYPE_ENUM;
      JavaType[] javaTypeArray0 = new JavaType[0];
      MapType mapType0 = MapType.construct((Class<?>) class1, (TypeBindings) null, (JavaType) simpleType0, javaTypeArray0, (JavaType) simpleType0, (JavaType) simpleType0);
      CollectionType collectionType0 = new CollectionType(mapType0, mapType0);
      ReferenceType referenceType0 = ReferenceType.construct((Class<?>) class0, (TypeBindings) null, (JavaType) collectionType0, javaTypeArray0, (JavaType) simpleType0);
      ReferenceType referenceType1 = referenceType0.withTypeHandler((Object) null);
      assertFalse(referenceType1.useStaticType());
      assertTrue(referenceType1.isAnchorType());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      SimpleType simpleType0 = TypeFactory.CORE_TYPE_INT;
      SimpleType simpleType1 = simpleType0.withStaticTyping();
      ReferenceType referenceType0 = ReferenceType.upgradeFrom(simpleType1, simpleType1);
      ReferenceType referenceType1 = referenceType0.withStaticTyping();
      assertTrue(referenceType1.isAnchorType());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Class<Object> class0 = Object.class;
      Class<ResolverStyle> class1 = ResolverStyle.class;
      TypeBindings typeBindings0 = TypeFactory.EMPTY_BINDINGS;
      SimpleType simpleType0 = TypeFactory.CORE_TYPE_BOOL;
      JavaType[] javaTypeArray0 = new JavaType[3];
      javaTypeArray0[2] = (JavaType) simpleType0;
      ReferenceType referenceType0 = ReferenceType.construct((Class<?>) class1, typeBindings0, (JavaType) simpleType0, javaTypeArray0, javaTypeArray0[2]);
      Object object0 = new Object();
      ReferenceType referenceType1 = new ReferenceType(class0, typeBindings0, referenceType0, javaTypeArray0, simpleType0, javaTypeArray0[2], object0, object0, false);
      ReferenceType referenceType2 = referenceType1.withStaticTyping();
      assertTrue(referenceType2.useStaticType());
      assertFalse(referenceType2.isAnchorType());
      assertFalse(referenceType0.useStaticType());
      assertTrue(referenceType0.isAnchorType());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      TypeFactory typeFactory0 = TypeFactory.instance;
      Class<LinkedHashSet> class0 = LinkedHashSet.class;
      CollectionType collectionType0 = typeFactory0.constructRawCollectionType(class0);
      ReferenceType referenceType0 = new ReferenceType(collectionType0, collectionType0);
      ReferenceType referenceType1 = referenceType0.withStaticTyping();
      assertTrue(referenceType1.useStaticType());
      assertFalse(referenceType1.isAnchorType());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Class<Object> class0 = Object.class;
      TypeBindings typeBindings0 = TypeFactory.EMPTY_BINDINGS;
      ResolvedRecursiveType resolvedRecursiveType0 = new ResolvedRecursiveType(class0, typeBindings0);
      Object object0 = new Object();
      ReferenceType referenceType0 = new ReferenceType(class0, typeBindings0, resolvedRecursiveType0, (JavaType[]) null, resolvedRecursiveType0, resolvedRecursiveType0, object0, resolvedRecursiveType0, true);
      ReferenceType referenceType1 = referenceType0.withContentValueHandler(object0);
      assertFalse(referenceType1.isAnchorType());
      assertNotSame(referenceType1, referenceType0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      SimpleType simpleType0 = TypeFactory.CORE_TYPE_INT;
      ReferenceType referenceType0 = ReferenceType.upgradeFrom(simpleType0, simpleType0);
      ReferenceType referenceType1 = referenceType0.withContentValueHandler(referenceType0);
      assertFalse(referenceType1.isAnchorType());
      assertTrue(referenceType1.equals((Object)referenceType0));
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Class<Object> class0 = Object.class;
      Class<ResolverStyle> class1 = ResolverStyle.class;
      TypeBindings typeBindings0 = TypeFactory.EMPTY_BINDINGS;
      SimpleType simpleType0 = TypeFactory.CORE_TYPE_BOOL;
      JavaType[] javaTypeArray0 = new JavaType[3];
      javaTypeArray0[2] = (JavaType) simpleType0;
      ReferenceType referenceType0 = ReferenceType.construct((Class<?>) class1, typeBindings0, (JavaType) simpleType0, javaTypeArray0, javaTypeArray0[2]);
      Object object0 = new Object();
      ReferenceType referenceType1 = new ReferenceType(class0, typeBindings0, referenceType0, javaTypeArray0, referenceType0, javaTypeArray0[2], object0, object0, false);
      ReferenceType referenceType2 = referenceType1.withContentValueHandler((Object) null);
      assertFalse(referenceType2.isAnchorType());
      assertSame(referenceType2, referenceType1);
      assertTrue(referenceType0.isAnchorType());
      assertFalse(referenceType0.useStaticType());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Class<Object> class0 = Object.class;
      TypeBindings typeBindings0 = TypeFactory.EMPTY_BINDINGS;
      ResolvedRecursiveType resolvedRecursiveType0 = new ResolvedRecursiveType(class0, typeBindings0);
      Object object0 = new Object();
      ReferenceType referenceType0 = new ReferenceType(class0, typeBindings0, resolvedRecursiveType0, (JavaType[]) null, resolvedRecursiveType0, resolvedRecursiveType0, object0, resolvedRecursiveType0, true);
      ReferenceType referenceType1 = referenceType0.withContentTypeHandler(resolvedRecursiveType0);
      assertFalse(referenceType1.isAnchorType());
      assertNotSame(referenceType1, referenceType0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Class<ResolverStyle> class0 = ResolverStyle.class;
      TypeBindings typeBindings0 = TypeFactory.EMPTY_BINDINGS;
      SimpleType simpleType0 = TypeFactory.CORE_TYPE_BOOL;
      JavaType[] javaTypeArray0 = new JavaType[3];
      javaTypeArray0[2] = (JavaType) simpleType0;
      ReferenceType referenceType0 = ReferenceType.construct((Class<?>) class0, typeBindings0, (JavaType) simpleType0, javaTypeArray0, javaTypeArray0[2]);
      CollectionLikeType collectionLikeType0 = CollectionLikeType.upgradeFrom(referenceType0, referenceType0);
      ReferenceType referenceType1 = referenceType0.withContentTypeHandler(collectionLikeType0);
      assertFalse(referenceType1.isAnchorType());
      assertTrue(referenceType0.isAnchorType());
      assertFalse(referenceType1.useStaticType());
      assertTrue(referenceType1.equals((Object)referenceType0));
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      SimpleType simpleType0 = TypeFactory.CORE_TYPE_COMPARABLE;
      ReferenceType referenceType0 = new ReferenceType(simpleType0, simpleType0);
      ReferenceType referenceType1 = referenceType0.withContentTypeHandler(simpleType0);
      assertFalse(referenceType1.isAnchorType());
      assertTrue(referenceType1.equals((Object)referenceType0));
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Class<Object> class0 = Object.class;
      TypeBindings typeBindings0 = TypeFactory.EMPTY_BINDINGS;
      SimpleType simpleType0 = TypeFactory.CORE_TYPE_BOOL;
      JavaType[] javaTypeArray0 = new JavaType[3];
      Object object0 = new Object();
      ReferenceType referenceType0 = new ReferenceType(class0, typeBindings0, simpleType0, javaTypeArray0, simpleType0, javaTypeArray0[2], object0, object0, false);
      ReferenceType referenceType1 = referenceType0.withContentTypeHandler((Object) null);
      assertTrue(referenceType1.isAnchorType());
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      TypeFactory typeFactory0 = TypeFactory.defaultInstance();
      Class<HashMap> class0 = HashMap.class;
      MapType mapType0 = typeFactory0.constructRawMapType(class0);
      ReferenceType referenceType0 = new ReferenceType(mapType0, mapType0);
      StringBuilder stringBuilder0 = new StringBuilder();
      ReferenceType referenceType1 = referenceType0.withContentTypeHandler(stringBuilder0);
      assertFalse(referenceType1.isAnchorType());
      assertTrue(referenceType1.equals((Object)referenceType0));
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Class<ResolverStyle> class0 = ResolverStyle.class;
      SimpleType simpleType0 = new SimpleType(class0);
      ReferenceType referenceType0 = ReferenceType.upgradeFrom(simpleType0, simpleType0);
      ReferenceType referenceType1 = referenceType0.withStaticTyping();
      ReferenceType referenceType2 = (ReferenceType)referenceType1.withContentType(referenceType1);
      assertFalse(referenceType2.equals((Object)referenceType0));
      assertTrue(referenceType2.useStaticType());
      assertFalse(referenceType1.isAnchorType());
      assertFalse(referenceType2.isAnchorType());
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      SimpleType simpleType0 = TypeFactory.CORE_TYPE_INT;
      ReferenceType referenceType0 = ReferenceType.upgradeFrom(simpleType0, simpleType0);
      ReferenceType referenceType1 = (ReferenceType)referenceType0.withContentType(simpleType0);
      assertTrue(referenceType1.isAnchorType());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Class<Object> class0 = Object.class;
      TypeBindings typeBindings0 = TypeFactory.EMPTY_BINDINGS;
      ResolvedRecursiveType resolvedRecursiveType0 = new ResolvedRecursiveType(class0, typeBindings0);
      JavaType[] javaTypeArray0 = new JavaType[1];
      javaTypeArray0[0] = (JavaType) resolvedRecursiveType0;
      ReferenceType referenceType0 = ReferenceType.construct((Class<?>) class0, typeBindings0, (JavaType) null, javaTypeArray0, (JavaType) resolvedRecursiveType0);
      ReferenceType referenceType1 = ReferenceType.upgradeFrom(javaTypeArray0[0], referenceType0);
      assertFalse(referenceType0.useStaticType());
      assertTrue(referenceType0.isAnchorType());
      assertFalse(referenceType1.equals((Object)referenceType0));
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Class<ResolvedRecursiveType> class0 = ResolvedRecursiveType.class;
      Class<Object> class1 = Object.class;
      SimpleType simpleType0 = TypeFactory.CORE_TYPE_ENUM;
      JavaType[] javaTypeArray0 = new JavaType[0];
      MapType mapType0 = MapType.construct((Class<?>) class1, (TypeBindings) null, (JavaType) simpleType0, javaTypeArray0, (JavaType) simpleType0, (JavaType) simpleType0);
      CollectionType collectionType0 = new CollectionType(mapType0, mapType0);
      ReferenceType referenceType0 = ReferenceType.construct((Class<?>) class0, (TypeBindings) null, (JavaType) collectionType0, javaTypeArray0, (JavaType) simpleType0);
      ReferenceType referenceType1 = referenceType0.withStaticTyping();
      ReferenceType referenceType2 = (ReferenceType)referenceType1.refine(class0, (TypeBindings) null, simpleType0, javaTypeArray0);
      assertTrue(referenceType2.useStaticType());
      assertFalse(referenceType1.isAnchorType());
      assertFalse(referenceType2.isAnchorType());
      assertTrue(referenceType2.equals((Object)referenceType0));
      assertTrue(referenceType0.isAnchorType());
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      SimpleType simpleType0 = TypeFactory.CORE_TYPE_INT;
      ReferenceType referenceType0 = new ReferenceType(simpleType0, simpleType0);
      Class<ResolverStyle> class0 = ResolverStyle.class;
      TypeBindings typeBindings0 = TypeBindings.createIfNeeded((Class<?>) class0, (JavaType) referenceType0);
      JavaType[] javaTypeArray0 = new JavaType[3];
      ReferenceType referenceType1 = (ReferenceType)referenceType0.refine(class0, typeBindings0, referenceType0, javaTypeArray0);
      assertFalse(referenceType1.isAnchorType());
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      LRUMap<Object, JavaType> lRUMap0 = new LRUMap<Object, JavaType>(2946, 2946);
      TypeFactory typeFactory0 = new TypeFactory(lRUMap0);
      Class<HashMap> class0 = HashMap.class;
      MapType mapType0 = typeFactory0.constructRawMapType(class0);
      MapType mapType1 = mapType0.withValueHandler(typeFactory0);
      ReferenceType referenceType0 = new ReferenceType(mapType1, mapType0);
      Class<Object> class1 = Object.class;
      JavaType[] javaTypeArray0 = new JavaType[6];
      ReferenceType referenceType1 = (ReferenceType)referenceType0.refine(class1, (TypeBindings) null, mapType1, javaTypeArray0);
      assertFalse(referenceType1.isAnchorType());
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Class<ResolverStyle> class0 = ResolverStyle.class;
      SimpleType simpleType0 = new SimpleType(class0);
      ReferenceType referenceType0 = ReferenceType.upgradeFrom(simpleType0, simpleType0);
      ReferenceType referenceType1 = referenceType0.withStaticTyping();
      JavaType javaType0 = referenceType1.getReferencedType();
      assertNotNull(javaType0);
      assertTrue(referenceType1.useStaticType());
      assertFalse(referenceType1.isAnchorType());
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      SimpleType simpleType0 = TypeFactory.CORE_TYPE_INT;
      ReferenceType referenceType0 = new ReferenceType(simpleType0, simpleType0);
      JavaType javaType0 = referenceType0.getReferencedType();
      assertTrue(javaType0.isConcrete());
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      TypeFactory typeFactory0 = TypeFactory.defaultInstance();
      Class<HashMap> class0 = HashMap.class;
      MapType mapType0 = typeFactory0.constructRawMapType(class0);
      ReferenceType referenceType0 = new ReferenceType(mapType0, mapType0);
      JavaType javaType0 = referenceType0.getReferencedType();
      assertTrue(javaType0.isConcrete());
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      TypeFactory typeFactory0 = TypeFactory.defaultInstance();
      Class<HashMap> class0 = HashMap.class;
      MapType mapType0 = typeFactory0.constructRawMapType(class0);
      ReferenceType referenceType0 = new ReferenceType(mapType0, mapType0);
      StringBuilder stringBuilder0 = new StringBuilder();
      referenceType0.getGenericSignature(stringBuilder0);
      assertEquals("Ljava/util/HashMap<Ljava/util/HashMap<Ljava/lang/Object;Ljava/lang/Object;>;>;", stringBuilder0.toString());
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      Class<ResolvedRecursiveType> class0 = ResolvedRecursiveType.class;
      Class<Object> class1 = Object.class;
      SimpleType simpleType0 = TypeFactory.CORE_TYPE_ENUM;
      JavaType[] javaTypeArray0 = new JavaType[0];
      MapType mapType0 = MapType.construct((Class<?>) class1, (TypeBindings) null, (JavaType) simpleType0, javaTypeArray0, (JavaType) simpleType0, (JavaType) simpleType0);
      CollectionType collectionType0 = new CollectionType(mapType0, mapType0);
      ReferenceType referenceType0 = ReferenceType.construct((Class<?>) class0, (TypeBindings) null, (JavaType) collectionType0, javaTypeArray0, (JavaType) simpleType0);
      StringBuilder stringBuilder0 = new StringBuilder("PROTECTED_AND_PUBLIC");
      referenceType0.getErasedSignature(stringBuilder0);
      assertEquals("PROTECTED_AND_PUBLICLcom/fasterxml/jackson/databind/type/ResolvedRecursiveType;", stringBuilder0.toString());
      assertTrue(referenceType0.isAnchorType());
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      Class<ResolverStyle> class0 = ResolverStyle.class;
      SimpleType simpleType0 = new SimpleType(class0);
      ReferenceType referenceType0 = ReferenceType.upgradeFrom(simpleType0, simpleType0);
      ReferenceType referenceType1 = referenceType0.withStaticTyping();
      JavaType javaType0 = referenceType1.getContentType();
      assertNotNull(javaType0);
      assertTrue(referenceType1.useStaticType());
      assertFalse(referenceType1.isAnchorType());
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      SimpleType simpleType0 = TypeFactory.CORE_TYPE_INT;
      ReferenceType referenceType0 = new ReferenceType(simpleType0, simpleType0);
      JavaType javaType0 = referenceType0.getContentType();
      assertTrue(javaType0.isConcrete());
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      LRUMap<Object, JavaType> lRUMap0 = new LRUMap<Object, JavaType>(2946, 2946);
      TypeFactory typeFactory0 = new TypeFactory(lRUMap0);
      Class<HashMap> class0 = HashMap.class;
      MapType mapType0 = typeFactory0.constructRawMapType(class0);
      ReferenceType referenceType0 = new ReferenceType(mapType0, mapType0);
      ReferenceType referenceType1 = referenceType0.withContentValueHandler(mapType0);
      JavaType javaType0 = referenceType1.getContentType();
      assertTrue(referenceType1.equals((Object)referenceType0));
      assertFalse(referenceType1.isAnchorType());
      assertTrue(javaType0.hasHandlers());
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      SimpleType simpleType0 = TypeFactory.CORE_TYPE_INT;
      SimpleType simpleType1 = simpleType0.withStaticTyping();
      ReferenceType referenceType0 = ReferenceType.upgradeFrom(simpleType1, simpleType1);
      JavaType javaType0 = referenceType0.getAnchorType();
      assertTrue(javaType0.isAbstract());
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      Class<Object> class0 = Object.class;
      JavaType javaType0 = TypeFactory.unknownType();
      JavaType[] javaTypeArray0 = new JavaType[5];
      javaTypeArray0[4] = javaType0;
      ReferenceType referenceType0 = ReferenceType.construct(class0, (TypeBindings) null, javaType0, javaTypeArray0, javaTypeArray0[4]);
      JavaType javaType1 = referenceType0.getAnchorType();
      assertFalse(javaType1.useStaticType());
      assertNotNull(javaType1);
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      Class<ResolverStyle> class0 = ResolverStyle.class;
      SimpleType simpleType0 = new SimpleType(class0);
      ReferenceType referenceType0 = ReferenceType.upgradeFrom(simpleType0, simpleType0);
      JavaType javaType0 = referenceType0.getAnchorType();
      assertFalse(javaType0.isInterface());
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      FileSystemHandling fileSystemHandling0 = new FileSystemHandling();
      SimpleType simpleType0 = TypeFactory.CORE_TYPE_INT;
      SimpleType simpleType1 = simpleType0.withValueHandler(fileSystemHandling0);
      ReferenceType referenceType0 = ReferenceType.upgradeFrom(simpleType1, simpleType1);
      JavaType javaType0 = referenceType0.getAnchorType();
      assertEquals(0, javaType0.containedTypeCount());
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      Class<ResolvedRecursiveType> class0 = ResolvedRecursiveType.class;
      SimpleType simpleType0 = SimpleType.constructUnsafe(class0);
      CollectionLikeType collectionLikeType0 = CollectionLikeType.upgradeFrom(simpleType0, simpleType0);
      JavaType[] javaTypeArray0 = new JavaType[5];
      javaTypeArray0[1] = (JavaType) simpleType0;
      ResolvedRecursiveType resolvedRecursiveType0 = new ResolvedRecursiveType(class0, (TypeBindings) null);
      ReferenceType referenceType0 = new ReferenceType(class0, (TypeBindings) null, collectionLikeType0, javaTypeArray0, simpleType0, javaTypeArray0[1], resolvedRecursiveType0, javaTypeArray0[4], true);
      JavaType javaType0 = referenceType0.getAnchorType();
      assertFalse(referenceType0.isAnchorType());
      assertNotNull(javaType0);
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      Class<ResolverStyle> class0 = ResolverStyle.class;
      SimpleType simpleType0 = new SimpleType(class0);
      ReferenceType referenceType0 = ReferenceType.upgradeFrom(simpleType0, simpleType0);
      String string0 = referenceType0.buildCanonicalName();
      assertEquals("java.time.format.ResolverStyle<java.time.format.ResolverStyle", string0);
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      SimpleType simpleType0 = TypeFactory.CORE_TYPE_INT;
      ReferenceType referenceType0 = new ReferenceType(simpleType0, simpleType0);
      Class<ResolverStyle> class0 = ResolverStyle.class;
      ReferenceType referenceType1 = (ReferenceType)referenceType0._narrow(class0);
      assertFalse(referenceType1.isAnchorType());
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      Class<Object> class0 = Object.class;
      TypeBindings typeBindings0 = TypeFactory.EMPTY_BINDINGS;
      ResolvedRecursiveType resolvedRecursiveType0 = new ResolvedRecursiveType(class0, typeBindings0);
      Object object0 = new Object();
      ReferenceType referenceType0 = new ReferenceType(class0, typeBindings0, resolvedRecursiveType0, (JavaType[]) null, resolvedRecursiveType0, resolvedRecursiveType0, object0, resolvedRecursiveType0, true);
      ReferenceType referenceType1 = (ReferenceType)referenceType0._narrow(class0);
      assertFalse(referenceType1.isAnchorType());
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      Class<Object> class0 = Object.class;
      SimpleType simpleType0 = SimpleType.constructUnsafe(class0);
      TypeBindings typeBindings0 = TypeBindings.createIfNeeded((Class<?>) class0, (JavaType) simpleType0);
      PlaceholderForType placeholderForType0 = new PlaceholderForType((-1056));
      JavaType[] javaTypeArray0 = new JavaType[9];
      javaTypeArray0[0] = (JavaType) placeholderForType0;
      javaTypeArray0[1] = (JavaType) placeholderForType0;
      Class<ResolverStyle> class1 = ResolverStyle.class;
      ResolvedRecursiveType resolvedRecursiveType0 = new ResolvedRecursiveType(class1, typeBindings0);
      Object object0 = new Object();
      ReferenceType referenceType0 = new ReferenceType(class0, typeBindings0, placeholderForType0, javaTypeArray0, javaTypeArray0[1], javaTypeArray0[2], resolvedRecursiveType0, object0, false);
      // Undeclared exception!
      try { 
        referenceType0.withContentTypeHandler(javaTypeArray0[0]);
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
         //
         // Operation should not be attempted on com.fasterxml.jackson.databind.type.PlaceholderForType
         //
         verifyException("com.fasterxml.jackson.databind.type.PlaceholderForType", e);
      }
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      SimpleType simpleType0 = TypeFactory.CORE_TYPE_COMPARABLE;
      ReferenceType referenceType0 = new ReferenceType(simpleType0, simpleType0);
      // Undeclared exception!
      try { 
        referenceType0.getGenericSignature((StringBuilder) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.fasterxml.jackson.databind.type.TypeBase", e);
      }
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      Class<ResolvedRecursiveType> class0 = ResolvedRecursiveType.class;
      SimpleType simpleType0 = SimpleType.constructUnsafe(class0);
      CollectionLikeType collectionLikeType0 = CollectionLikeType.upgradeFrom(simpleType0, simpleType0);
      JavaType[] javaTypeArray0 = new JavaType[5];
      ResolvedRecursiveType resolvedRecursiveType0 = new ResolvedRecursiveType(class0, (TypeBindings) null);
      ReferenceType referenceType0 = new ReferenceType(class0, (TypeBindings) null, collectionLikeType0, javaTypeArray0, simpleType0, javaTypeArray0[1], resolvedRecursiveType0, javaTypeArray0[4], true);
      // Undeclared exception!
      try { 
        referenceType0.getErasedSignature((StringBuilder) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.fasterxml.jackson.databind.type.TypeBase", e);
      }
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      Class<ResolvedRecursiveType> class0 = ResolvedRecursiveType.class;
      Class<Object> class1 = Object.class;
      SimpleType simpleType0 = TypeFactory.CORE_TYPE_ENUM;
      JavaType[] javaTypeArray0 = new JavaType[0];
      MapType mapType0 = MapType.construct((Class<?>) class1, (TypeBindings) null, (JavaType) simpleType0, javaTypeArray0, (JavaType) simpleType0, (JavaType) simpleType0);
      CollectionType collectionType0 = new CollectionType(mapType0, mapType0);
      ReferenceType referenceType0 = ReferenceType.construct((Class<?>) class0, (TypeBindings) null, (JavaType) collectionType0, javaTypeArray0, (JavaType) simpleType0);
      Object object0 = new Object();
      ReferenceType referenceType1 = referenceType0.withContentTypeHandler(object0);
      boolean boolean0 = referenceType0.equals(referenceType1);
      assertTrue(boolean0);
      assertTrue(referenceType0.isAnchorType());
      assertFalse(referenceType1.isAnchorType());
      assertFalse(referenceType1.useStaticType());
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      Class<Object> class0 = Object.class;
      TypeBindings typeBindings0 = TypeFactory.EMPTY_BINDINGS;
      ResolvedRecursiveType resolvedRecursiveType0 = new ResolvedRecursiveType(class0, typeBindings0);
      Object object0 = new Object();
      ReferenceType referenceType0 = new ReferenceType(class0, typeBindings0, resolvedRecursiveType0, (JavaType[]) null, resolvedRecursiveType0, resolvedRecursiveType0, object0, resolvedRecursiveType0, true);
      boolean boolean0 = referenceType0.equals((Object) null);
      assertFalse(referenceType0.isAnchorType());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      SimpleType simpleType0 = TypeFactory.CORE_TYPE_INT;
      ReferenceType referenceType0 = new ReferenceType(simpleType0, simpleType0);
      boolean boolean0 = referenceType0.equals(referenceType0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      SimpleType simpleType0 = TypeFactory.CORE_TYPE_COMPARABLE;
      ReferenceType referenceType0 = new ReferenceType(simpleType0, simpleType0);
      Object object0 = new Object();
      boolean boolean0 = referenceType0.equals(object0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      Class<Object> class0 = Object.class;
      TypeBindings typeBindings0 = TypeFactory.EMPTY_BINDINGS;
      ResolvedRecursiveType resolvedRecursiveType0 = new ResolvedRecursiveType(class0, typeBindings0);
      JavaType[] javaTypeArray0 = new JavaType[1];
      ReferenceType referenceType0 = ReferenceType.construct((Class<?>) class0, typeBindings0, (JavaType) null, javaTypeArray0, (JavaType) resolvedRecursiveType0);
      boolean boolean0 = referenceType0.isAnchorType();
      assertTrue(boolean0);
      assertFalse(referenceType0.useStaticType());
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      Class<ResolvedRecursiveType> class0 = ResolvedRecursiveType.class;
      TypeBindings typeBindings0 = TypeFactory.EMPTY_BINDINGS;
      Class<Object> class1 = Object.class;
      ResolvedRecursiveType resolvedRecursiveType0 = new ResolvedRecursiveType(class1, typeBindings0);
      ReferenceType referenceType0 = new ReferenceType(class0, typeBindings0, resolvedRecursiveType0, (JavaType[]) null, resolvedRecursiveType0, resolvedRecursiveType0, class1, typeBindings0, true);
      boolean boolean0 = referenceType0.isAnchorType();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test49()  throws Throwable  {
      SimpleType simpleType0 = TypeFactory.CORE_TYPE_COMPARABLE;
      ReferenceType referenceType0 = new ReferenceType(simpleType0, simpleType0);
      ReferenceType referenceType1 = referenceType0.withStaticTyping();
      assertTrue(referenceType1.useStaticType());
      assertFalse(referenceType1.isAnchorType());
  }

  @Test(timeout = 4000)
  public void test50()  throws Throwable  {
      Class<ResolverStyle> class0 = ResolverStyle.class;
      TypeBindings typeBindings0 = TypeFactory.EMPTY_BINDINGS;
      SimpleType simpleType0 = TypeFactory.CORE_TYPE_BOOL;
      JavaType[] javaTypeArray0 = new JavaType[3];
      javaTypeArray0[2] = (JavaType) simpleType0;
      ReferenceType referenceType0 = ReferenceType.construct((Class<?>) class0, typeBindings0, (JavaType) simpleType0, javaTypeArray0, javaTypeArray0[2]);
      ReferenceType referenceType1 = referenceType0.withContentValueHandler((Object) null);
      assertFalse(referenceType1.useStaticType());
      assertTrue(referenceType1.isAnchorType());
  }

  @Test(timeout = 4000)
  public void test51()  throws Throwable  {
      SimpleType simpleType0 = TypeFactory.CORE_TYPE_COMPARABLE;
      ReferenceType referenceType0 = new ReferenceType(simpleType0, simpleType0);
      Object object0 = new Object();
      ReferenceType referenceType1 = referenceType0.withContentValueHandler(object0);
      JavaType javaType0 = referenceType1.getReferencedType();
      assertFalse(referenceType1.isAnchorType());
      assertTrue(javaType0.hasValueHandler());
      assertTrue(referenceType1.equals((Object)referenceType0));
      assertNotNull(javaType0);
  }

  @Test(timeout = 4000)
  public void test52()  throws Throwable  {
      Class<Object> class0 = Object.class;
      JavaType javaType0 = TypeFactory.unknownType();
      JavaType[] javaTypeArray0 = new JavaType[5];
      javaTypeArray0[4] = javaType0;
      ReferenceType referenceType0 = ReferenceType.construct(class0, (TypeBindings) null, javaType0, javaTypeArray0, javaTypeArray0[4]);
      ReferenceType referenceType1 = referenceType0.withValueHandler(javaTypeArray0[2]);
      assertTrue(referenceType1.isAnchorType());
      assertFalse(referenceType1.useStaticType());
  }

  @Test(timeout = 4000)
  public void test53()  throws Throwable  {
      Class<Object> class0 = Object.class;
      TypeBindings typeBindings0 = TypeFactory.EMPTY_BINDINGS;
      ResolvedRecursiveType resolvedRecursiveType0 = new ResolvedRecursiveType(class0, typeBindings0);
      JavaType[] javaTypeArray0 = new JavaType[1];
      ReferenceType referenceType0 = ReferenceType.construct((Class<?>) class0, typeBindings0, (JavaType) null, javaTypeArray0, (JavaType) resolvedRecursiveType0);
      Object object0 = new Object();
      ReferenceType referenceType1 = referenceType0.withValueHandler(object0);
      ReferenceType referenceType2 = (ReferenceType)referenceType1.withContentType(resolvedRecursiveType0);
      assertFalse(referenceType2.useStaticType());
      assertFalse(referenceType2.isAnchorType());
      assertTrue(referenceType0.isAnchorType());
      assertSame(referenceType2, referenceType1);
  }

  @Test(timeout = 4000)
  public void test54()  throws Throwable  {
      SimpleType simpleType0 = TypeFactory.CORE_TYPE_INT;
      ReferenceType referenceType0 = new ReferenceType(simpleType0, simpleType0);
      Class<ResolvedRecursiveType> class0 = ResolvedRecursiveType.class;
      TypeBindings typeBindings0 = TypeBindings.emptyBindings();
      ResolvedRecursiveType resolvedRecursiveType0 = new ResolvedRecursiveType(class0, typeBindings0);
      ReferenceType referenceType1 = referenceType0.withContentTypeHandler(resolvedRecursiveType0);
      assertTrue(referenceType1.equals((Object)referenceType0));
      assertFalse(referenceType1.isAnchorType());
  }

  @Test(timeout = 4000)
  public void test55()  throws Throwable  {
      Class<Object> class0 = Object.class;
      TypeBindings typeBindings0 = TypeFactory.EMPTY_BINDINGS;
      ResolvedRecursiveType resolvedRecursiveType0 = new ResolvedRecursiveType(class0, typeBindings0);
      Object object0 = new Object();
      ReferenceType referenceType0 = new ReferenceType(class0, typeBindings0, resolvedRecursiveType0, (JavaType[]) null, resolvedRecursiveType0, resolvedRecursiveType0, object0, resolvedRecursiveType0, true);
      ReferenceType referenceType1 = referenceType0.withTypeHandler(resolvedRecursiveType0);
      assertFalse(referenceType1.isAnchorType());
      assertSame(referenceType1, referenceType0);
  }

  @Test(timeout = 4000)
  public void test56()  throws Throwable  {
      SimpleType simpleType0 = TypeFactory.CORE_TYPE_COMPARABLE;
      ReferenceType referenceType0 = new ReferenceType(simpleType0, simpleType0);
      ReferenceType referenceType1 = referenceType0.withTypeHandler(simpleType0);
      ReferenceType referenceType2 = (ReferenceType)referenceType0.withContentType(referenceType1);
      ReferenceType referenceType3 = (ReferenceType)referenceType2.getReferencedType();
      assertTrue(referenceType3.equals((Object)referenceType0));
      assertFalse(referenceType3.isAnchorType());
      assertNotNull(referenceType3);
      assertFalse(referenceType2.isAnchorType());
      assertFalse(referenceType2.equals((Object)referenceType1));
  }

  @Test(timeout = 4000)
  public void test57()  throws Throwable  {
      SimpleType simpleType0 = TypeFactory.CORE_TYPE_COMPARABLE;
      ReferenceType referenceType0 = new ReferenceType(simpleType0, simpleType0);
      // Undeclared exception!
      try { 
        ReferenceType.upgradeFrom((JavaType) null, referenceType0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.fasterxml.jackson.databind.type.ReferenceType", e);
      }
  }

  @Test(timeout = 4000)
  public void test58()  throws Throwable  {
      JavaType[] javaTypeArray0 = new JavaType[5];
      // Undeclared exception!
      try { 
        ReferenceType.upgradeFrom(javaTypeArray0[4], javaTypeArray0[1]);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Missing referencedType
         //
         verifyException("com.fasterxml.jackson.databind.type.ReferenceType", e);
      }
  }

  @Test(timeout = 4000)
  public void test59()  throws Throwable  {
      SimpleType simpleType0 = TypeFactory.CORE_TYPE_COMPARABLE;
      ReferenceType referenceType0 = new ReferenceType(simpleType0, simpleType0);
      ReferenceType referenceType1 = ReferenceType.upgradeFrom(simpleType0, referenceType0);
      assertFalse(referenceType1.equals((Object)referenceType0));
  }

  @Test(timeout = 4000)
  public void test60()  throws Throwable  {
      SimpleType simpleType0 = TypeFactory.CORE_TYPE_COMPARABLE;
      ReferenceType referenceType0 = new ReferenceType(simpleType0, simpleType0);
      JavaType javaType0 = referenceType0.getContentType();
      assertFalse(javaType0.isMapLikeType());
  }

  @Test(timeout = 4000)
  public void test61()  throws Throwable  {
      SimpleType simpleType0 = TypeFactory.CORE_TYPE_COMPARABLE;
      ReferenceType referenceType0 = new ReferenceType(simpleType0, simpleType0);
      JavaType javaType0 = referenceType0.getAnchorType();
      assertSame(referenceType0, javaType0);
  }

  @Test(timeout = 4000)
  public void test62()  throws Throwable  {
      Class<Object> class0 = Object.class;
      // Undeclared exception!
      try { 
        ReferenceType.construct(class0, (JavaType) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.fasterxml.jackson.databind.type.ReferenceType", e);
      }
  }

  @Test(timeout = 4000)
  public void test63()  throws Throwable  {
      Class<Object> class0 = Object.class;
      TypeBindings typeBindings0 = TypeFactory.EMPTY_BINDINGS;
      ResolvedRecursiveType resolvedRecursiveType0 = new ResolvedRecursiveType(class0, typeBindings0);
      Object object0 = new Object();
      ReferenceType referenceType0 = new ReferenceType(class0, typeBindings0, resolvedRecursiveType0, (JavaType[]) null, resolvedRecursiveType0, resolvedRecursiveType0, object0, resolvedRecursiveType0, true);
      boolean boolean0 = referenceType0.hasContentType();
      assertTrue(boolean0);
      assertFalse(referenceType0.isAnchorType());
  }

  @Test(timeout = 4000)
  public void test64()  throws Throwable  {
      SimpleType simpleType0 = TypeFactory.CORE_TYPE_COMPARABLE;
      ReferenceType referenceType0 = new ReferenceType(simpleType0, simpleType0);
      String string0 = referenceType0.toString();
      assertEquals("[reference type, class java.lang.Comparable<java.lang.Comparable<[simple type, class java.lang.Comparable]>]", string0);
  }

  @Test(timeout = 4000)
  public void test65()  throws Throwable  {
      Class<Object> class0 = Object.class;
      TypeBindings typeBindings0 = TypeFactory.EMPTY_BINDINGS;
      ResolvedRecursiveType resolvedRecursiveType0 = new ResolvedRecursiveType(class0, typeBindings0);
      JavaType[] javaTypeArray0 = new JavaType[1];
      ReferenceType referenceType0 = ReferenceType.construct((Class<?>) class0, typeBindings0, (JavaType) null, javaTypeArray0, (JavaType) resolvedRecursiveType0);
      boolean boolean0 = referenceType0.isReferenceType();
      assertTrue(boolean0);
      assertTrue(referenceType0.isAnchorType());
      assertFalse(referenceType0.useStaticType());
  }

  @Test(timeout = 4000)
  public void test66()  throws Throwable  {
      Class<Object> class0 = Object.class;
      TypeBindings typeBindings0 = TypeFactory.EMPTY_BINDINGS;
      ResolvedRecursiveType resolvedRecursiveType0 = new ResolvedRecursiveType(class0, typeBindings0);
      JavaType[] javaTypeArray0 = new JavaType[1];
      ReferenceType referenceType0 = ReferenceType.construct((Class<?>) class0, typeBindings0, (JavaType) null, javaTypeArray0, (JavaType) resolvedRecursiveType0);
      JavaType javaType0 = referenceType0.getReferencedType();
      assertNotNull(javaType0);
      assertTrue(referenceType0.isAnchorType());
      assertFalse(referenceType0.useStaticType());
  }
}
