/*
 * This file was automatically generated by EvoSuite
 * Wed Sep 30 19:04:34 GMT 2026
 */

package com.google.javascript.jscomp;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.google.javascript.jscomp.AbstractCompiler;
import com.google.javascript.jscomp.CheckLevel;
import com.google.javascript.jscomp.Compiler;
import com.google.javascript.jscomp.MethodCheck;
import com.google.javascript.rhino.Node;
import com.google.javascript.rhino.ScriptOrFnNode;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class MethodCompilerPass_ESTest extends MethodCompilerPass_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Compiler compiler0 = new Compiler();
      CheckLevel checkLevel0 = CheckLevel.OFF;
      Node node0 = compiler0.parseSyntheticCode("", "");
      Node node1 = new Node(64, node0, node0, node0);
      MethodCheck methodCheck0 = new MethodCheck(compiler0, checkLevel0);
      // Undeclared exception!
      try { 
        methodCheck0.process(node1, node1);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Compiler compiler0 = new Compiler();
      CheckLevel checkLevel0 = CheckLevel.OFF;
      Node node0 = Node.newString("9C");
      Node node1 = new Node(34, node0, 10, 86);
      MethodCheck methodCheck0 = new MethodCheck(compiler0, checkLevel0);
      // Undeclared exception!
      try { 
        methodCheck0.process(node1, node0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // INTERNAL COMPILER ERROR.
         // Please report this problem.
         // null
         //
         verifyException("com.google.common.base.Preconditions", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Compiler compiler0 = new Compiler();
      CheckLevel checkLevel0 = CheckLevel.OFF;
      Node node0 = new Node(64);
      Node node1 = new Node(64, node0, node0, node0);
      MethodCheck methodCheck0 = new MethodCheck(compiler0, checkLevel0);
      methodCheck0.process(node0, node0);
      assertEquals(4095, Node.COLUMN_MASK);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Compiler compiler0 = new Compiler();
      CheckLevel checkLevel0 = CheckLevel.OFF;
      ScriptOrFnNode scriptOrFnNode0 = (ScriptOrFnNode)compiler0.parseSyntheticCode("dC", "com.google.javascript.jscomp.MethodCompilerPass$GatherSignatures");
      Node node0 = new Node(64, scriptOrFnNode0, scriptOrFnNode0, scriptOrFnNode0);
      MethodCheck methodCheck0 = new MethodCheck(compiler0, checkLevel0);
      methodCheck0.process(scriptOrFnNode0, scriptOrFnNode0);
      assertNull(scriptOrFnNode0.getSourceName());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Compiler compiler0 = new Compiler();
      CheckLevel checkLevel0 = CheckLevel.OFF;
      Node node0 = Node.newString("dC");
      Node node1 = new Node(31, node0, node0, node0, node0, 2, 2);
      Node node2 = new Node(64, node1, 10, 86);
      MethodCheck methodCheck0 = new MethodCheck(compiler0, checkLevel0);
      // Undeclared exception!
      try { 
        methodCheck0.process(node2, node0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Compiler compiler0 = new Compiler();
      CheckLevel checkLevel0 = CheckLevel.OFF;
      Node node0 = Node.newString("dC");
      Node node1 = new Node(64, node0, 10, 86);
      MethodCheck methodCheck0 = new MethodCheck(compiler0, checkLevel0);
      // Undeclared exception!
      try { 
        methodCheck0.process(node1, node0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      CheckLevel checkLevel0 = CheckLevel.WARNING;
      MethodCheck methodCheck0 = new MethodCheck((AbstractCompiler) null, checkLevel0);
      // Undeclared exception!
      try { 
        methodCheck0.process((Node) null, (Node) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.google.javascript.jscomp.NodeTraversal", e);
      }
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Compiler compiler0 = new Compiler();
      CheckLevel checkLevel0 = CheckLevel.OFF;
      MethodCheck methodCheck0 = new MethodCheck(compiler0, checkLevel0);
      Node node0 = Node.newString("dC");
      Node node1 = new Node(64, node0, node0, node0);
      Node node2 = new Node(64, node1, 10, 86);
      // Undeclared exception!
      try { 
        methodCheck0.process(node2, node0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
      }
  }
}
