/*
 * This file was automatically generated by EvoSuite
 * Thu Oct 01 14:14:43 GMT 2026
 */

package org.apache.commons.math3.optimization.univariate;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.commons.math3.analysis.UnivariateFunction;
import org.apache.commons.math3.analysis.function.Asinh;
import org.apache.commons.math3.analysis.function.Atanh;
import org.apache.commons.math3.analysis.function.Cosh;
import org.apache.commons.math3.analysis.function.Sinc;
import org.apache.commons.math3.analysis.function.Sinh;
import org.apache.commons.math3.analysis.function.Tan;
import org.apache.commons.math3.optimization.ConvergenceChecker;
import org.apache.commons.math3.optimization.GoalType;
import org.apache.commons.math3.optimization.univariate.BrentOptimizer;
import org.apache.commons.math3.optimization.univariate.UnivariatePointValuePair;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class BrentOptimizer_ESTest extends BrentOptimizer_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      BrentOptimizer brentOptimizer0 = new BrentOptimizer(0.11256109178066254, 0.11256109178066254);
      GoalType goalType0 = GoalType.MAXIMIZE;
      Cosh cosh0 = new Cosh();
      UnivariatePointValuePair univariatePointValuePair0 = brentOptimizer0.optimize(1574, (UnivariateFunction) cosh0, goalType0, 1.7215153848731208E166, 760.6475);
      assertEquals(959.0552338993568, univariatePointValuePair0.getPoint(), 0.01);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      BrentOptimizer brentOptimizer0 = new BrentOptimizer(760.6475, 760.6475);
      Atanh atanh0 = new Atanh();
      GoalType goalType0 = GoalType.MINIMIZE;
      brentOptimizer0.optimize(1233, (UnivariateFunction) atanh0, goalType0, 2.185301053838889E-9, 2.185301053838889E-9, 0.0);
      UnivariatePointValuePair univariatePointValuePair0 = brentOptimizer0.doOptimize();
      assertNotNull(univariatePointValuePair0);
      assertEquals(0.0, univariatePointValuePair0.getValue(), 0.01);
      assertEquals(0.0, univariatePointValuePair0.getPoint(), 0.01);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      BrentOptimizer brentOptimizer0 = new BrentOptimizer(3.0, 3.0);
      Sinc sinc0 = new Sinc(true);
      GoalType goalType0 = GoalType.MINIMIZE;
      brentOptimizer0.optimize(2144785930, (UnivariateFunction) sinc0, goalType0, (double) 2144785930, 3.0, 1043.191);
      UnivariatePointValuePair univariatePointValuePair0 = brentOptimizer0.doOptimize();
      assertEquals((-5.147922854103282E-5), univariatePointValuePair0.getValue(), 0.01);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      BrentOptimizer brentOptimizer0 = null;
      try {
        brentOptimizer0 = new BrentOptimizer((-553.0), 1206);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // -553 is smaller than the minimum (0)
         //
         verifyException("org.apache.commons.math3.optimization.univariate.BrentOptimizer", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      BrentOptimizer brentOptimizer0 = new BrentOptimizer(760.6475, 760.6475);
      Atanh atanh0 = new Atanh();
      GoalType goalType0 = GoalType.MAXIMIZE;
      UnivariatePointValuePair univariatePointValuePair0 = brentOptimizer0.optimize(1233, (UnivariateFunction) atanh0, goalType0, 3.4430307697462206E166, 3.4430307697462206E166, 0.0);
      assertEquals(4.506924106737164E150, univariatePointValuePair0.getPoint(), 0.01);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      BrentOptimizer brentOptimizer0 = new BrentOptimizer(760.6475, 760.6475);
      Atanh atanh0 = new Atanh();
      GoalType goalType0 = GoalType.MINIMIZE;
      brentOptimizer0.optimize(1233, (UnivariateFunction) atanh0, goalType0, 1200.116999539248, (-1695.4021337187));
      UnivariatePointValuePair univariatePointValuePair0 = brentOptimizer0.doOptimize();
      assertEquals(Double.NaN, univariatePointValuePair0.getValue(), 0.01);
      assertEquals((-247.64256708972607), univariatePointValuePair0.getPoint(), 0.01);
      assertNotNull(univariatePointValuePair0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      BrentOptimizer brentOptimizer0 = new BrentOptimizer(1.0, 14.101419448852539);
      Tan tan0 = new Tan();
      GoalType goalType0 = GoalType.MINIMIZE;
      UnivariatePointValuePair univariatePointValuePair0 = brentOptimizer0.optimize(1542, (UnivariateFunction) tan0, goalType0, (-2160.87654607), (double) 1542, (double) 1542);
      assertEquals((-0.10834250721062738), univariatePointValuePair0.getValue(), 0.01);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      BrentOptimizer brentOptimizer0 = new BrentOptimizer(0.11256109178066254, 0.11256109178066254);
      Asinh asinh0 = new Asinh();
      GoalType goalType0 = GoalType.MAXIMIZE;
      UnivariatePointValuePair univariatePointValuePair0 = brentOptimizer0.optimize(1574, (UnivariateFunction) asinh0, goalType0, (double) 1574, 0.11256109178066254);
      assertEquals(1416.8637053576078, univariatePointValuePair0.getPoint(), 0.01);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      BrentOptimizer brentOptimizer0 = new BrentOptimizer(3.0, 3.0);
      Sinh sinh0 = new Sinh();
      GoalType goalType0 = GoalType.MINIMIZE;
      UnivariatePointValuePair univariatePointValuePair0 = brentOptimizer0.optimize(1206, (UnivariateFunction) sinh0, goalType0, 0.5, 1080.438273035, 0.5);
      assertEquals(74.20321057778875, univariatePointValuePair0.getValue(), 0.01);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      BrentOptimizer brentOptimizer0 = null;
      try {
        brentOptimizer0 = new BrentOptimizer(7.157830361617945, (-463.7955404714), (ConvergenceChecker<UnivariatePointValuePair>) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // -463.796 is smaller than, or equal to, the minimum (0)
         //
         verifyException("org.apache.commons.math3.optimization.univariate.BrentOptimizer", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      BrentOptimizer brentOptimizer0 = null;
      try {
        brentOptimizer0 = new BrentOptimizer((-518.714386343818), 0.5, (ConvergenceChecker<UnivariatePointValuePair>) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // -518.714 is smaller than the minimum (0)
         //
         verifyException("org.apache.commons.math3.optimization.univariate.BrentOptimizer", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      BrentOptimizer brentOptimizer0 = new BrentOptimizer(0.5, 0.5);
      // Undeclared exception!
      try { 
        brentOptimizer0.doOptimize();
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // illegal state: maximal count (0) exceeded: evaluations
         //
         verifyException("org.apache.commons.math3.optimization.univariate.BaseAbstractUnivariateOptimizer", e);
      }
  }
}
