/*
 * This file was automatically generated by EvoSuite
 * Wed Sep 30 20:05:02 GMT 2026
 */

package com.google.javascript.jscomp;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.google.javascript.jscomp.Compiler;
import com.google.javascript.jscomp.FunctionTypeBuilder;
import com.google.javascript.jscomp.JSSourceFile;
import com.google.javascript.jscomp.Scope;
import com.google.javascript.jscomp.TightenTypes;
import com.google.javascript.rhino.JSDocInfo;
import com.google.javascript.rhino.Node;
import com.google.javascript.rhino.jstype.FunctionType;
import com.google.javascript.rhino.jstype.JSType;
import com.google.javascript.rhino.jstype.JSTypeRegistry;
import com.google.javascript.rhino.jstype.ObjectType;
import com.google.javascript.rhino.jstype.StaticScope;
import java.io.File;
import java.nio.charset.Charset;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.io.MockFile;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class FunctionTypeBuilder_ESTest extends FunctionTypeBuilder_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Compiler compiler0 = new Compiler();
      Node node0 = compiler0.parseTestCode("");
      FunctionTypeBuilder functionTypeBuilder0 = new FunctionTypeBuilder("=p^(!fhvEo{?~~", compiler0, node0, "=p^(!fhvEo{?~~", (Scope) null);
      // Undeclared exception!
      try { 
        functionTypeBuilder0.inferParameterTypes((JSDocInfo) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.google.javascript.jscomp.FunctionTypeBuilder", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      JSDocInfo jSDocInfo0 = new JSDocInfo();
      boolean boolean0 = FunctionTypeBuilder.isFunctionTypeDeclaration(jSDocInfo0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Compiler compiler0 = new Compiler();
      File file0 = MockFile.createTempFile("variable length argument must be last", "variable length argument must be last");
      Charset charset0 = Charset.defaultCharset();
      JSSourceFile jSSourceFile0 = JSSourceFile.fromFile(file0, charset0);
      Node node0 = compiler0.parse(jSSourceFile0);
      FunctionTypeBuilder functionTypeBuilder0 = new FunctionTypeBuilder("variable length argument must be last", compiler0, node0, "variable length argument must be last", (Scope) null);
      // Undeclared exception!
      try { 
        functionTypeBuilder0.buildAndRegister();
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // All Function types must have params and a return type
         //
         verifyException("com.google.javascript.jscomp.FunctionTypeBuilder", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Compiler compiler0 = new Compiler();
      Node node0 = compiler0.parseTestCode("j|rq-HnL NzyJJrI");
      FunctionTypeBuilder functionTypeBuilder0 = new FunctionTypeBuilder("=p^(!fhvEo{?~~", compiler0, node0, "=p^(!fhvEo{?~~", (Scope) null);
      FunctionTypeBuilder functionTypeBuilder1 = functionTypeBuilder0.inferParameterTypes(node0, (JSDocInfo) null);
      functionTypeBuilder1.buildAndRegister();
      FunctionType functionType0 = functionTypeBuilder1.buildAndRegister();
      assertFalse(functionType0.hasCachedValues());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Compiler compiler0 = new Compiler();
      Node node0 = compiler0.parseTestCode("j|rq-HnL NzyJJrI");
      FunctionTypeBuilder functionTypeBuilder0 = new FunctionTypeBuilder("9rOf", compiler0, node0, "9rOf", (Scope) null);
      JSDocInfo jSDocInfo0 = new JSDocInfo();
      FunctionTypeBuilder functionTypeBuilder1 = functionTypeBuilder0.inferTemplateTypeName(jSDocInfo0);
      assertSame(functionTypeBuilder0, functionTypeBuilder1);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Compiler compiler0 = new Compiler();
      Node node0 = compiler0.parseTestCode("j|rq-HnL NzyJJrI");
      FunctionTypeBuilder functionTypeBuilder0 = new FunctionTypeBuilder("=p^(!fhvEo{?~~", compiler0, node0, "=p^(!fhvEo{?~~", (Scope) null);
      FunctionTypeBuilder functionTypeBuilder1 = functionTypeBuilder0.inferTemplateTypeName((JSDocInfo) null);
      assertSame(functionTypeBuilder1, functionTypeBuilder0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Compiler compiler0 = new Compiler();
      Node[] nodeArray0 = new Node[1];
      Node node0 = compiler0.parseTestCode("Akq33qy?rS");
      nodeArray0[0] = node0;
      Node node1 = new Node(83, nodeArray0);
      Scope scope0 = new Scope(node1, compiler0);
      FunctionTypeBuilder functionTypeBuilder0 = new FunctionTypeBuilder("parameter {0} does not appear in {1}''s parameter list", compiler0, nodeArray0[0], "parameter {0} does not appear in {1}''s parameter list", scope0);
      // Undeclared exception!
      try { 
        functionTypeBuilder0.inferParameterTypes(node1, (JSDocInfo) null);
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
         //
         // BLOCK [sourcename: java.lang.String@0000000482] is not a string node
         //
         verifyException("com.google.javascript.rhino.Node", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Compiler compiler0 = new Compiler();
      Node node0 = compiler0.parseTestCode("j|rq-HnL NzyJJrI");
      FunctionTypeBuilder functionTypeBuilder0 = new FunctionTypeBuilder("9rOf", compiler0, node0, "9rOf", (Scope) null);
      JSDocInfo jSDocInfo0 = new JSDocInfo();
      FunctionTypeBuilder functionTypeBuilder1 = functionTypeBuilder0.inferParameterTypes(jSDocInfo0);
      assertSame(functionTypeBuilder1, functionTypeBuilder0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Compiler compiler0 = new Compiler();
      Node node0 = compiler0.parseTestCode("Akq33qy?rS");
      Scope scope0 = new Scope(node0, compiler0);
      FunctionTypeBuilder functionTypeBuilder0 = new FunctionTypeBuilder("parameter {0} does not appear in {1}''s araeter list", compiler0, node0, "VAR", scope0);
      FunctionTypeBuilder functionTypeBuilder1 = functionTypeBuilder0.inferThisType((JSDocInfo) null, (Node) null);
      assertSame(functionTypeBuilder0, functionTypeBuilder1);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Compiler compiler0 = new Compiler();
      Node node0 = compiler0.parseTestCode("j|rq-HnL NzyJJrI");
      FunctionTypeBuilder functionTypeBuilder0 = new FunctionTypeBuilder("9rOf", compiler0, node0, "9rOf", (Scope) null);
      JSDocInfo jSDocInfo0 = new JSDocInfo();
      // Undeclared exception!
      try { 
        functionTypeBuilder0.inferThisType(jSDocInfo0, node0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.google.javascript.rhino.jstype.JSTypeRegistry", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Compiler compiler0 = new Compiler();
      Node node0 = compiler0.parseTestCode("j|rq-HnL NzyJJrI");
      FunctionTypeBuilder functionTypeBuilder0 = new FunctionTypeBuilder("=p^(!fhvEo{?~~", compiler0, node0, "=p^(!fhvEo{?~~", (Scope) null);
      // Undeclared exception!
      try { 
        functionTypeBuilder0.inferThisType((JSDocInfo) null, node0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.google.javascript.rhino.jstype.JSTypeRegistry", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Compiler compiler0 = new Compiler();
      Node node0 = compiler0.parseTestCode("j|rq-HnL NzyJJrI");
      FunctionTypeBuilder functionTypeBuilder0 = new FunctionTypeBuilder("=p^(!fhvEo{?~~", compiler0, node0, "=p^(!fhvEo{?~~", (Scope) null);
      JSTypeRegistry jSTypeRegistry0 = compiler0.getTypeRegistry();
      JSType[] jSTypeArray0 = new JSType[0];
      FunctionType functionType0 = jSTypeRegistry0.createConstructorType((JSType) null, jSTypeArray0);
      FunctionTypeBuilder functionTypeBuilder1 = functionTypeBuilder0.inferThisType((JSDocInfo) null, functionType0);
      assertSame(functionTypeBuilder0, functionTypeBuilder1);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Compiler compiler0 = new Compiler();
      Node node0 = compiler0.parseTestCode("j|rq-HnL NzyJJrI");
      FunctionTypeBuilder functionTypeBuilder0 = new FunctionTypeBuilder("9rOf", compiler0, node0, "9rOf", (Scope) null);
      JSDocInfo jSDocInfo0 = new JSDocInfo();
      TightenTypes tightenTypes0 = new TightenTypes(compiler0);
      JSTypeRegistry jSTypeRegistry0 = tightenTypes0.getTypeRegistry();
      Node node1 = Node.newString("j|rq-HnL NzyJJrI", 38, (-768));
      JSType jSType0 = jSTypeRegistry0.createFromTypeNodes(node1, "$1_ij", (StaticScope<JSType>) null, false);
      ObjectType objectType0 = ObjectType.cast(jSType0);
      LinkedList<JSType> linkedList0 = new LinkedList<JSType>();
      JSType jSType1 = jSTypeRegistry0.createFunctionTypeWithVarArgs(objectType0, jSType0, (List<JSType>) linkedList0);
      FunctionTypeBuilder functionTypeBuilder1 = functionTypeBuilder0.inferThisType(jSDocInfo0, jSType1);
      assertSame(functionTypeBuilder1, functionTypeBuilder0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Compiler compiler0 = new Compiler();
      Node node0 = compiler0.parseTestCode("W");
      FunctionTypeBuilder functionTypeBuilder0 = new FunctionTypeBuilder("=p^(!fhvEona{:~~", compiler0, node0, "=p^(!fhvEona{:~~", (Scope) null);
      FunctionTypeBuilder functionTypeBuilder1 = functionTypeBuilder0.inferThisType((JSDocInfo) null, (JSType) null);
      assertSame(functionTypeBuilder1, functionTypeBuilder0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Compiler compiler0 = new Compiler();
      Node node0 = compiler0.parseTestCode("j|rq-HnL NzyJJrI");
      FunctionTypeBuilder functionTypeBuilder0 = new FunctionTypeBuilder("9rOf", compiler0, node0, "9rOf", (Scope) null);
      JSDocInfo jSDocInfo0 = new JSDocInfo();
      functionTypeBuilder0.inferInheritance(jSDocInfo0);
      assertEquals(0, compiler0.getWarningCount());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Compiler compiler0 = new Compiler();
      Node[] nodeArray0 = new Node[1];
      Node node0 = compiler0.parseTestCode("Akq33qy?rS");
      nodeArray0[0] = node0;
      Scope scope0 = new Scope(node0, compiler0);
      FunctionTypeBuilder functionTypeBuilder0 = new FunctionTypeBuilder("parameter {0} does not appear in {1}''s parameter list", compiler0, nodeArray0[0], "parameter {0} does not appear in {1}''s parameter list", scope0);
      FunctionTypeBuilder functionTypeBuilder1 = functionTypeBuilder0.inferInheritance((JSDocInfo) null);
      assertSame(functionTypeBuilder1, functionTypeBuilder0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Compiler compiler0 = new Compiler();
      Node node0 = compiler0.parseTestCode("j|rq-HnL NzyJJrI");
      FunctionTypeBuilder functionTypeBuilder0 = new FunctionTypeBuilder("9rOf", compiler0, node0, "9rOf", (Scope) null);
      JSDocInfo jSDocInfo0 = new JSDocInfo();
      FunctionTypeBuilder functionTypeBuilder1 = functionTypeBuilder0.inferReturnType(jSDocInfo0);
      assertSame(functionTypeBuilder0, functionTypeBuilder1);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Compiler compiler0 = new Compiler();
      Node node0 = compiler0.parseTestCode("j|rq-HnL NzyJJrI");
      FunctionTypeBuilder functionTypeBuilder0 = new FunctionTypeBuilder("=p^(!fhvEo{?~~", compiler0, node0, "=p^(!fhvEo{?~~", (Scope) null);
      FunctionTypeBuilder functionTypeBuilder1 = functionTypeBuilder0.inferReturnType((JSDocInfo) null);
      assertSame(functionTypeBuilder0, functionTypeBuilder1);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Compiler compiler0 = new Compiler();
      Node node0 = compiler0.parseTestCode("W");
      FunctionTypeBuilder functionTypeBuilder0 = new FunctionTypeBuilder("=p^(!fhvEona{:~~", compiler0, node0, "=p^(!fhvEona{:~~", (Scope) null);
      JSTypeRegistry jSTypeRegistry0 = compiler0.getTypeRegistry();
      JSType jSType0 = jSTypeRegistry0.createNamedType("com.google.javascript.jscomp.FunctionTypeBuilder", "KAHUA6X#Yfe1EAG[", 50, (-3834));
      FunctionType functionType0 = jSTypeRegistry0.createFunctionType(jSType0, node0);
      FunctionTypeBuilder functionTypeBuilder1 = functionTypeBuilder0.inferFromOverriddenFunction(functionType0, node0);
      assertSame(functionTypeBuilder0, functionTypeBuilder1);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Compiler compiler0 = new Compiler();
      Node node0 = compiler0.parseTestCode("j|rq-HnL NzyJJrI");
      FunctionTypeBuilder functionTypeBuilder0 = new FunctionTypeBuilder("9rOf", compiler0, node0, "9rOf", (Scope) null);
      FunctionTypeBuilder functionTypeBuilder1 = functionTypeBuilder0.setSourceNode(node0);
      JSDocInfo jSDocInfo0 = new JSDocInfo();
      FunctionTypeBuilder functionTypeBuilder2 = functionTypeBuilder1.inferParameterTypes(node0, jSDocInfo0);
      // Undeclared exception!
      try { 
        functionTypeBuilder2.buildAndRegister();
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.google.common.base.Preconditions", e);
      }
  }
}
